### ISSUE TITLE
Allow async functions to generate streams

### ISSUE THREAD

**Issue by GabrielLomba** [sedenardi/node-stream-concat#10]
The stream generating function called [here](https://github.com/sedenardi/node-stream-concat/blob/29f63b6cb8561d039ed88e247266aba578ea58a2/index.js#L22) is currently synchronous.

I have ran into a case where streams can error due to HTTP connection timeout (AWS S3 read streams), meaning the array API is not enough for them since we can have a situation where we concat 10 streams and the first 2 streams take a while to be processed, timing out the next 8.

Since the nextStream function is internal, this should not break any APIs (the lib doesn't try catch the current synchronous version so no I don't see a need to try catch the async version either).

I'm willing to submit a PR.

**Comment by sedenardi** [comment]
Feel free to submit a PR! Please add a test for an async stream that matches your use case.

**Comment by sedenardi** [comment]
Closed by https://github.com/sedenardi/node-stream-concat/pull/11
