### ISSUE TITLE
How to catch error inside StreamConcat? 

### ISSUE THREAD

**Issue by geertbrit** [sedenardi/node-stream-concat#12]
Say I have the contrived example: 

const rawStream = new StreamConcat() => {
  throw new Error('how to catch this"?")
})

How would I catch the error?

**Comment by sedenardi** [comment]
Thanks for the question. I believe the `StreamConcat` instance will emit an `error` event, since the error happens within the 
`Transform` methods implemented by `StreamConcat`. I have not tested this, but it should be easy to confirm.

**Comment by sedenardi** [comment]
See https://github.com/sedenardi/node-stream-concat/pull/15 for potential fix.
