### ISSUE TITLE
Deal with 'close' event

### ISSUE THREAD

**Issue by uwburn** [sedenardi/node-stream-concat#4]
Hello, i'm using this module to concatenate some transform streams, and, on certain occasions, i need to call on them `.destroy()` as i want to discard the rest of the data.

In the current implementation of `stream-concat`, the next stream is concatenated when the current stream emits `'end'` event, but calling `.destroy()` causes the current stream to emit `'close'` instead.

Would be admissible (maybe with some option to enable this specific feature) to move onto the next stream by listening also `'close'` event? If so i can provide PR for it.

Oh, and thank you for your great module! 👍

**Comment by sedenardi** [comment]
Interesting feature. Out of curiosity, what's your use case?

Feel free to submit a PR. Make sure you put the feature behind an option flag, so the default behavior is preserved, and include at least one test. I'll take a look at it as soon as I can.

**Comment by uwburn** [comment]
I'm reading data from multiple db (Cassandra) result streams, each of them with different granularity based on how old are the data: i then need to merge the data in a single stream, switching to 'finer' granularity streams as the data is more recent and i also need to support pagination. So, at some point i just need to discard the data of a stream: i can do that by just reading all the data and filtering them out in the stream transformation, but that can be slow, or, since node 8, is possible to call `.destroy()` to terminate prematurely.

I have update the implementation to listen the `'close'` event, but i need to arrange a test and update the readme. I will report back when it's done.

**Comment by sedenardi** [comment]
Sounds good. I'll take a look whenever you send it over.

**Comment by uwburn** [comment]
PR sent. ;)

**Comment by sedenardi** [comment]
Handled in https://github.com/sedenardi/node-stream-concat/pull/5

**Comment by uwburn** [comment]
Thank you, it was a pleasure to contribute.

**Comment by sedenardi** [comment]
No problem, always happy to have contributors.
