### ISSUE TITLE
MaxListenersExceededWarning: Possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by raine** [sedenardi/node-stream-concat#8]
What's the correct way to dispose of a stream created with this library?

I'm creating these in express request handler, and after a few requests a `MaxListenersExceededWarning` appears.

Tried something like this to no avail:

```javascript
app.get('/stdin', (req, res) => {
  const readStream = fs.createReadStream(tmpFilePath, { flags: 'r' })
  combined = new StreamConcat([readStream, stdin])
  combined.pipe(res)
  req.on('close', () => {
    combined.destroy()
  })
})
```

I can only guess it's binding events on `stdin`. That's the only thing persisting across requests there.

**Comment by raine** [comment]
Not sure if `_destroy` is implemented entirely right here but this fixes the warning for me:

```diff
diff --git i/index.js w/index.js
index ea6d019..5edd3e2 100644
--- i/index.js
+++ w/index.js
@@ -28,7 +28,7 @@ var StreamConcat = function(streams, options) {
     } else {
       self.currentStream.pipe(self, {end: false});
       var streamClosed = false;
-      var goNext = function() {
+      self.goNext = function() {
         if (streamClosed) {
           return;
         }
@@ -36,9 +36,9 @@ var StreamConcat = function(streams, options) {
         nextStream();
       };
 
-      self.currentStream.on('end', goNext);
+      self.currentStream.on('end', self.goNext);
       if (options.advanceOnClose) {
-        self.currentStream.on('close', goNext);
+        self.currentStream.on('close', self.goNext);
       }
     }
   };
@@ -48,6 +48,14 @@ var StreamConcat = function(streams, options) {
 
 util.inherits(StreamConcat, Transform);
 
+StreamConcat.prototype._destroy = function() {
+  this.end();
+  if (this.currentStream) {
+    this.currentStream.removeListener('end', this.goNext)
+    this.currentStream.removeListener('close', this.goNext)
+  }
+};
+
 StreamConcat.prototype._transform = function(chunk, encoding, callback) {
   callback(null, chunk);
 };
```

**Comment by sedenardi** [comment]
Try instead to remove the event listeners from `currentStream` in the `nextStream` function, perhaps inside the `goNext` function. Your code seems to only remove the event listeners from the last stream used by the `StreamConcat` stream. Doing it inside the `goNext` function, right before `nextStream` is called, should ensure you're removing the listeners from each underlying stream used by the `StreamConcat` stream.

Let me know if that also solves your issue. If all tests pass then feel free to submit a pull request and I'll publish it to NPM after I review it. Thanks for your help!

**Comment by raine** [comment]
I'll try this soon. Thanks!

**Comment by sedenardi** [comment]
Closing this for now. Feel free to let me know if it's still an issue.
